# Generated by Django 2.1.5 on 2020-08-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default="no", max_length=16),
        ),
    ]
