# Generated by Django 2.1.5 on 2020-08-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
