# Generated by Django 2.1.5 on 2020-08-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.ForeignKey(on_delete='CASCADE', to='store.address')),
            ],
        ),
    ]
