# Generated by Django 2.1.5 on 2020-08-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
