# Generated by Django 2.1.5 on 2020-08-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20200808_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='user_id',
        ),
    ]
