# Generated by Django 2.1.5 on 2020-08-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_address_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_id',
        ),
    ]
